import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import { resolve } from 'path'

dotenv.config({ path: resolve(__dirname, '../.env.local') })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

const opportunities = [
  // ===== HACKATHONS (Devpost — актуальные) =====
  {
    title: 'Build with Gemini XPRIZE',
    category: 'Хакатон',
    direction: 'Программирование',
    format: 'Онлайн',
    deadline: '2026-08-17',
    description: 'Глобальный хакатон с призовым фондом $2M. Создай продукт с использованием Gemini AI для образования или продуктивности.',
    requirements: 'Команда или соло. Любой стек с Gemini API.',
    apply_url: 'https://xprize.devpost.com/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['ai', 'gemini', 'продукт'],
    required_skill_tags: ['программирование'],
  },
  {
    title: 'USAII Global AI Hackathon 2026',
    category: 'Хакатон',
    direction: 'STEM',
    format: 'Онлайн',
    deadline: '2026-06-21',
    description: 'AI-хакатон для новичков и опытных разработчиков. Призы $15,000. Темы: social good, ML/AI.',
    requirements: 'Beginner friendly. Регистрация на Devpost.',
    apply_url: 'https://usaii-global-ai-hackathon-2026.devpost.com/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['ai', 'social good', 'beginner'],
    required_skill_tags: ['программирование'],
  },
  {
    title: 'Global AI Hackathon with Qwen Cloud',
    category: 'Хакатон',
    direction: 'Программирование',
    format: 'Онлайн',
    deadline: '2026-07-09',
    description: 'Создай AI-продукт с Qwen Cloud. Призы $45,000. Темы: AI, дизайн, продуктивность.',
    requirements: 'Опыт с AI/ML приветствуется. Любой язык.',
    apply_url: 'https://qwencloud-hackathon.devpost.com/',
    grade_level: ['10', '11', '12'],
    tags: ['ai', 'cloud', 'qwen'],
    required_skill_tags: ['программирование'],
  },
  {
    title: 'NextGenHacks',
    category: 'Хакатон',
    direction: 'Социальное влияние',
    format: 'Онлайн',
    deadline: '2026-06-19',
    description: 'Хакатон для школьников и студентов. Beginner friendly, open ended, social good.',
    requirements: 'Для начинающих. Регистрация на Devpost.',
    apply_url: 'https://nextgenhacks.devpost.com/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['beginner', 'social good', 'open ended'],
    required_skill_tags: [],
  },
  {
    title: 'Youth Code x AI',
    category: 'Хакатон',
    direction: 'Программирование',
    format: 'Онлайн',
    deadline: '2026-06-27',
    description: 'Молодёжный хакатон: мобильные и веб-приложения с AI. Призы $2,700.',
    requirements: 'Beginner friendly. Мобильные / Web проекты.',
    apply_url: 'https://youth-code-x-ai-29376.devpost.com/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['ai', 'mobile', 'web', 'youth'],
    required_skill_tags: ['программирование'],
  },
  {
    title: 'United Hacks V7',
    category: 'Хакатон',
    direction: 'STEM',
    format: 'Онлайн',
    deadline: '2026-07-12',
    description: 'Международный хакатон для школьников. Beginner friendly, education, design. Призы $26,350.',
    requirements: 'Для начинающих. Команда или соло.',
    apply_url: 'https://unitedhacksv7.devpost.com/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['education', 'design', 'beginner'],
    required_skill_tags: [],
  },
  {
    title: 'LaunchHacks V',
    category: 'Хакатон',
    direction: 'Программирование',
    format: 'Онлайн',
    deadline: '2026-12-15',
    description: 'Хакатон с фокусом на education и AI. Призы $17,575. Beginner friendly.',
    requirements: 'Новички приветствуются. Регистрация на Devpost.',
    apply_url: 'https://launchhacks-v.devpost.com/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['education', 'ai', 'beginner'],
    required_skill_tags: [],
  },
  {
    title: 'GitLab Transcend Hackathon',
    category: 'Хакатон',
    direction: 'Программирование',
    format: 'Онлайн',
    deadline: '2026-06-24',
    description: 'Хакатон от GitLab: AI, DevOps, продуктивность. Призы $20,000.',
    requirements: 'Опыт с Git приветствуется.',
    apply_url: 'https://gitlab-transcend.devpost.com/',
    grade_level: ['10', '11', '12'],
    tags: ['devops', 'ai', 'gitlab'],
    required_skill_tags: ['программирование'],
  },
  {
    title: 'Hack for Humanity | Summer 2026',
    category: 'Хакатон',
    direction: 'Социальное влияние',
    format: 'Онлайн',
    deadline: '2026-09-04',
    description: 'Хакатон для социального блага: здоровье, AI, доступность. Beginner friendly.',
    requirements: 'Для начинающих. Открыт для всех.',
    apply_url: 'https://hack-for-humanity-summer-26.devpost.com/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['health', 'social good', 'beginner'],
    required_skill_tags: [],
  },
  {
    title: 'UC Berkeley AI Hackathon 2026',
    category: 'Хакатон',
    direction: 'STEM',
    format: 'Онлайн',
    deadline: '2026-06-21',
    description: 'AI-хакатон от UC Berkeley. Beginner friendly, ML/AI.',
    requirements: 'Открыт для всех возрастов.',
    apply_url: 'https://ai-hackathon-2026.devpost.com/',
    grade_level: ['10', '11', '12'],
    tags: ['ai', 'berkeley', 'beginner'],
    required_skill_tags: ['программирование'],
  },
  // ===== SUMMER SCHOOLS (Europe) =====
  {
    title: 'Migration, Economy and Society — LSE Summer School',
    category: 'Летняя школа',
    direction: 'Социальное влияние',
    format: 'Офлайн',
    deadline: '2026-07-01',
    description: 'Трёхнедельная программа в Лондоне по миграции, экономике и обществу. 7.5 кредитов ECTS.',
    requirements: 'Английский B2+. Мотивационное письмо.',
    apply_url: 'https://www.summerschoolsineurope.eu/course/global-migration-and-health/',
    grade_level: ['11', '12'],
    tags: ['лондон', 'социология', 'кредиты'],
    required_skill_tags: [],
  },
  {
    title: 'Bootcamp IA — Nice, France',
    category: 'Летняя школа',
    direction: 'Программирование',
    format: 'Офлайн',
    deadline: '2026-07-15',
    description: 'Недельный буткемп по искусственному интеллекту в Ницце, Франция. Практика и проекты.',
    requirements: 'Базовые знания программирования.',
    apply_url: 'https://www.summerschoolsineurope.eu/course/bootcamp-ia-nice/',
    grade_level: ['10', '11', '12'],
    tags: ['ai', 'франция', 'буткемп'],
    required_skill_tags: ['программирование'],
  },
  {
    title: 'Founding Europe — Utrecht Summer School',
    category: 'Летняя школа',
    direction: 'Наука',
    format: 'Офлайн',
    deadline: '2026-06-20',
    description: 'Программа в Утрехте (Нидерланды) по истории Европы. 8 ECTS кредитов. 4 недели.',
    requirements: 'Английский B2+.',
    apply_url: 'https://www.summerschoolsineurope.eu/course/founding-europe-from-antiquity-to-the-19th-century/',
    grade_level: ['11', '12'],
    tags: ['история', 'нидерланды', 'кредиты'],
    required_skill_tags: [],
  },
  {
    title: 'Future through Stories — Literature & Film (Utrecht)',
    category: 'Летняя школа',
    direction: 'Социальное влияние',
    format: 'Офлайн',
    deadline: '2026-07-31',
    description: 'Анализ литературы и кино о будущем. 2.5 ECTS. Утрехтский университет.',
    requirements: 'Английский B2+.',
    apply_url: 'https://www.summerschoolsineurope.eu/course/exploring-the-future-through-stories-in-literature-and-film/',
    grade_level: ['11', '12'],
    tags: ['литература', 'кино', 'нидерланды'],
    required_skill_tags: [],
  },
  // ===== TOP SUMMER PROGRAMS (из базы знаний) =====
  {
    title: 'RSI — Research Science Institute (MIT/CEE)',
    category: 'Летняя школа',
    direction: 'STEM',
    format: 'Офлайн',
    deadline: '2026-12-01',
    description: 'Топ-1 летняя программа для школьников. 6 недель STEM-research в MIT. Полностью бесплатно. Отбор ~2%.',
    requirements: '15-18 лет, выдающиеся академические результаты, исследовательский интерес.',
    apply_url: 'https://www.cee.org/programs/research-science-institute',
    grade_level: ['10', '11'],
    tags: ['mit', 'research', 'stem', 'бесплатно'],
    required_skill_tags: [],
  },
  {
    title: 'MITES — MIT Introduction to Technology',
    category: 'Летняя школа',
    direction: 'STEM',
    format: 'Офлайн',
    deadline: '2026-11-01',
    description: 'Летняя STEM-программа MIT для мотивированных старшеклассников. Полностью бесплатная.',
    requirements: '15-18 лет, из underrepresented backgrounds приветствуются.',
    apply_url: 'https://mites.mit.edu',
    grade_level: ['10', '11'],
    tags: ['mit', 'stem', 'бесплатно', 'diversity'],
    required_skill_tags: [],
  },
  {
    title: 'YYGS — Yale Young Global Scholars',
    category: 'Летняя школа',
    direction: 'Социальное влияние',
    format: 'Офлайн',
    deadline: '2026-11-15',
    description: 'Двухнедельная программа Yale для школьников со всего мира. Междисциплинарные семинары.',
    requirements: '15-17 лет, мотивационное эссе, рекомендательное письмо.',
    apply_url: 'https://globalscholars.yale.edu',
    grade_level: ['10', '11'],
    tags: ['yale', 'leadership', 'global'],
    required_skill_tags: [],
  },
  {
    title: 'SSP — Summer Science Program',
    category: 'Летняя школа',
    direction: 'Наука',
    format: 'Офлайн',
    deadline: '2027-02-01',
    description: 'Астрофизика или биохимия: 5 недель научного исследования. Полностью бесплатная программа.',
    requirements: 'Сильная мотивация к науке, 10-11 класс.',
    apply_url: 'https://summerscience.org',
    grade_level: ['10', '11'],
    tags: ['астрономия', 'биохимия', 'research', 'бесплатно'],
    required_skill_tags: [],
  },
  // ===== SCHOLARSHIPS =====
  {
    title: 'Стипендия Türkiye Burslari 2026',
    category: 'Стипендия',
    direction: 'Социальное влияние',
    format: 'Онлайн',
    deadline: '2027-02-20',
    description: 'Полная стипендия для бакалавриата в Турции: обучение, проживание, стипендия. 160+ вузов.',
    requirements: 'GPA > 70%, до 21 года для бакалавриата.',
    apply_url: 'https://www.turkiyeburslari.gov.tr',
    grade_level: ['11', '12'],
    tags: ['турция', 'полная стипендия', 'бакалавр'],
    required_skill_tags: [],
  },
  {
    title: 'Stipendium Hungaricum — Венгрия',
    category: 'Стипендия',
    direction: 'Наука',
    format: 'Онлайн',
    deadline: '2027-01-15',
    description: 'Полная стипендия в Венгрии: 100+ программ на английском. Бакалавриат, магистратура.',
    requirements: 'Аттестат/диплом, мотивационное письмо, английский B2.',
    apply_url: 'https://stipendiumhungaricum.hu',
    grade_level: ['11', '12'],
    tags: ['венгрия', 'полная стипендия', 'европа'],
    required_skill_tags: [],
  },
  {
    title: 'DAAD Scholarship — Германия',
    category: 'Стипендия',
    direction: 'STEM',
    format: 'Онлайн',
    deadline: '2026-10-15',
    description: 'Стипендии DAAD для обучения в Германии. Множество программ на английском.',
    requirements: 'Отличные оценки, мотивационное письмо, языковой сертификат.',
    apply_url: 'https://www.daad.de/en/',
    grade_level: ['11', '12'],
    tags: ['германия', 'stem', 'европа'],
    required_skill_tags: [],
  },
  {
    title: 'Global Korea Scholarship (GKS)',
    category: 'Стипендия',
    direction: 'STEM',
    format: 'Онлайн',
    deadline: '2027-03-01',
    description: 'Полная стипендия для бакалавриата в Южной Корее: год языка + 4 года обучения.',
    requirements: 'GPA > 80%, до 25 лет, гражданство стран-партнёров.',
    apply_url: 'https://www.studyinkorea.go.kr',
    grade_level: ['11', '12'],
    tags: ['корея', 'полная стипендия', 'бакалавр'],
    required_skill_tags: [],
  },
  {
    title: 'MEXT Scholarship — Япония',
    category: 'Стипендия',
    direction: 'Наука',
    format: 'Онлайн',
    deadline: '2027-04-01',
    description: 'Полная стипендия правительства Японии: обучение + проживание + стипендия. Бакалавриат.',
    requirements: 'До 24 лет, рекомендация посольства.',
    apply_url: 'https://www.studyinjapan.go.jp',
    grade_level: ['11', '12'],
    tags: ['япония', 'полная стипендия', 'бакалавр'],
    required_skill_tags: [],
  },
  // ===== OLYMPIADS =====
  {
    title: 'Международная олимпиада по информатике (IOI)',
    category: 'Олимпиада',
    direction: 'Программирование',
    format: 'Офлайн',
    deadline: '2027-03-01',
    description: 'Крупнейшая олимпиада по программированию для школьников. Алгоритмы и структуры данных.',
    requirements: 'Отбор через национальную олимпиаду. Возраст до 19 лет.',
    apply_url: 'https://ioinformatics.org',
    grade_level: ['9', '10', '11', '12'],
    tags: ['алгоритмы', 'программирование', 'международная'],
    required_skill_tags: ['программирование'],
  },
  {
    title: 'Regeneron ISEF — Научная ярмарка',
    category: 'Конкурс',
    direction: 'Наука',
    format: 'Гибрид',
    deadline: '2026-11-01',
    description: 'Крупнейшая научная ярмарка для школьников в мире. Индивидуальные исследовательские проекты.',
    requirements: 'Научный проект, отбор через региональные фэйры.',
    apply_url: 'https://www.societyforscience.org/isef/',
    grade_level: ['9', '10', '11', '12'],
    tags: ['research', 'наука', 'международная'],
    required_skill_tags: [],
  },
  {
    title: 'Conrad Challenge — Innovation',
    category: 'Конкурс',
    direction: 'Бизнес',
    format: 'Онлайн',
    deadline: '2026-10-31',
    description: 'Конкурс инноваций и предпринимательства для школьников 13-18 лет. Командный проект.',
    requirements: 'Команда 2-5 человек, 13-18 лет.',
    apply_url: 'https://www.conradchallenge.org',
    grade_level: ['9', '10', '11', '12'],
    tags: ['инновации', 'стартап', 'командная работа'],
    required_skill_tags: [],
  },
  {
    title: 'Diamond Challenge — Стартап-конкурс',
    category: 'Конкурс',
    direction: 'Бизнес',
    format: 'Онлайн',
    deadline: '2027-01-10',
    description: 'Стартап-конкурс для школьников: бизнес-идея или социальная инициатива.',
    requirements: 'Школьники 14-18 лет. Бизнес-план + питч.',
    apply_url: 'https://diamondchallenge.org',
    grade_level: ['9', '10', '11', '12'],
    tags: ['стартап', 'бизнес', 'питч'],
    required_skill_tags: [],
  },
]

async function main() {
  console.log('Удаляем старые данные...')
  await supabase.from('opportunities').delete().neq('id', '00000000-0000-0000-0000-000000000000')

  console.log(`Загружаем ${opportunities.length} возможностей...`)
  const { data, error } = await supabase.from('opportunities').insert(opportunities).select()

  if (error) {
    console.error('Ошибка:', error)
    process.exit(1)
  }

  console.log(`Загружено ${data.length} возможностей`)
  process.exit(0)
}

main()
